const supabase = require('../database/supabaseClient');

const createTable = async () => {
    try {
        // SQL para criar a tabela
        const sql = `
            create table if not exists teste (
                id bigint generated by default as identity primary key,
                coluna_teste text,
                created_at timestamp with time zone default timezone('utc'::text, now()) not null
            );
        `;

        // Executar o SQL
        const { data, error } = await supabase.rpc('exec_sql', { query: sql });

        if (error) {
            console.error('Erro ao criar tabela:', error);
            return;
        }

        console.log('Tabela criada com sucesso!');
    } catch (err) {
        console.error('Erro:', err);
    }
};

// Executar a função
createTable(); 