-- Create the teste table
create table if not exists teste (
    id bigint generated by default as identity primary key,
    coluna_teste text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
); 