-- Equivalente ao Sequelize:
-- connection.define("Teste", {
--   coluna_teste: DataTypes.STRING
-- });

-- No Supabase/PostgreSQL:
create table if not exists teste (
    id bigint generated by default as identity primary key,
    coluna_teste text,  -- Equivalente ao DataTypes.STRING
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Criar um trigger para atualizar o updated_at automaticamente
create or replace function update_updated_at_column()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

create trigger update_teste_updated_at
    before update on teste
    for each row
    execute function update_updated_at_column(); 