-- Sequelize:
-- connection.define("Exemplo", {
--   texto: DataTypes.STRING,
--   numero: DataTypes.INTEGER,
--   booleano: DataTypes.BOOLEAN,
--   data: DataTypes.DATE,
--   json: DataTypes.JSON,
--   lista: DataTypes.ARRAY(DataTypes.STRING)
-- });

-- No Supabase/PostgreSQL:
create table if not exists exemplo (
    id bigint generated by default as identity primary key,
    texto text,
    numero integer,
    booleano boolean,
    data timestamp with time zone,
    json jsonb,
    lista text[],
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
); 